train:
    epoch: 1000
    snapshot_interval: 2000
    batchsize: 16
    validsize: 12

dataset:
    extension: ".png"
    train_size: 256
    valid_size: 256
    color_space: "rgb"
    line_space: "rgb"
    line_method: ["xdog", "pencil", "blend"]

model:
    generator:
        num_layers: 4
        attn_type: "sa"
        lr: 0.0001
        b1: 0.5
        b2: 0.99
        mode: "train"
    discriminator:
        lr: 0.0002
        b1: 0.5
        b2: 0.99
        mode: "train"

loss:
    content: 1.0
    adv: 0.01
    pef: 0.001